'''
This module parses the requests.csv 
file generated by blokada and creates
a text file of the blocked and accepted
requests.
'''

LOGFILE = '/sdcard/Download/blokada/requests.csv'
ACCEPTED = 'a'
BLOCKED = 'b'

class Requests(object):
    def __init__(self, logfile=LOGFILE):
        self.logfile = logfile
        self.accepted = set()
        self.blocked = set()
        with open(self.logfile) as log:
            for line in log.readlines():
                _, state, host = line.split(',')
                if '.' not in host:
                    continue

                if state == BLOCKED:
                    self.blocked.add(host)
                if state == ACCEPTED:
                    self.accepted.add(host)
    
        with open('accepted.txt', 'w') as f:
            f.writelines(self.accepted)

        with open('blocked.txt', 'w') as f:
            f.writelines(self.blocked)

    @property
    def hosts(self):
        hosts = set()
        for host in self.accepted:
            hosts.add(host)
        for host in self.blocked:
            hosts.add(host)
        return hosts


r = Requests()


print(len(r.hosts))