{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "A simple guessing game.\n",
    "\n",
    "Step 1: Generate a random int between 1, 10\n",
    "Step 2: Prompt the user to input a number between 1, 10\n",
    "Step 3: Compare the number entered by the user with the \n",
    "        number generated by the computer. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import random\n",
    "\n",
    "def random_number():\n",
    "    return random.randint(1, 10)\n",
    "\n",
    "def guess():\n",
    "    return int(input(\"Guess a number between 1-10: \"))\n",
    "    \n",
    "\n",
    "def game():\n",
    "    while True:\n",
    "        if guess() == random_number():\n",
    "            print('You Win :)')\n",
    "            break\n",
    "        else:\n",
    "            print('You Fail :( ')\n",
    "\n",
    "            "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
